### ISSUE TITLE
Warnings when making py_loader

### ISSUE THREAD

**Issue by inimeseke** [metacall/core#239] opened 2022-01-25 15:52 UTC
## 🐛 Bug Report

running `make py_loader` in the build folder after doing `cmake ..` and `cmake -DOPTION_BUILD_BACKTRACE=OFF -DOPTION_BUILD_TESTS=OFF -DOPTION_BUILD_LOADERS_PY=ON ..` gives

```
[  0%] Building C object source/metacall/CMakeFiles/metacall.dir/__/version/source/version.c.o
[  0%] Building C object source/metacall/CMakeFiles/metacall.dir/__/preprocessor/source/preprocessor.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment_variable.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment_variable_path.c.o
[  4%] Building C object source/metacall/CMakeFiles/metacall.dir/__/format/source/format.c.o
[  4%] Building C object source/metacall/CMakeFiles/metacall.dir/__/format/source/format_print.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/backtrace/source/backtrace.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/backtrace/source/backtrace_none.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/threading/source/threading.c.o
[  9%] Building C object source/metacall/CMakeFiles/metacall.dir/__/threading/source/threading_thread_id.c.o
[  9%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log.c.o
[ 11%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_valid_size.c.o
[ 11%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_map.c.o
[ 11%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_level.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_record.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_handle.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy.c.o
[ 16%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect.c.o
[ 16%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_impl.c.o
[ 19%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_singleton.c.o
[ 19%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format.c.o
[ 19%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_binary.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_custom.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_text.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule.c.o
[ 23%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule_async.c.o
[ 23%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule_sync.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage_batch.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage_sequential.c.o
[ 28%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream.c.o
[ 28%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_custom.c.o
[ 28%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_file.c.o
[ 30%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_nginx.c.o
[ 30%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_socket.c.o
[ 33%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_stdio.c.o
[ 33%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_syslog.c.o
/Users/mart/metacall/core/source/log/source/log_policy_stream_syslog.c:114:32: warning: unused variable 'syslog_data' [-Wunused-variable]
        log_policy_stream_syslog_data syslog_data = log_policy_instance(policy);
                                      ^
/Users/mart/metacall/core/source/log/source/log_policy_stream_syslog.c:112:74: warning: unused parameter 'buffer' [-Wunused-parameter]
static int log_policy_stream_syslog_write(log_policy policy, const void *buffer, const size_t size)
                                                                         ^
2 warnings generated.
[ 33%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_format.c.o
[ 35%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_schedule.c.o
[ 35%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_stream.c.o
[ 35%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_storage.c.o
[ 38%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory.c.o
[ 38%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator.c.o
[ 40%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_std.c.o
[ 40%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_std_impl.c.o
[ 40%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_nginx.c.o
[ 42%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_nginx_impl.c.o
[ 42%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability.c.o
[ 42%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability_executable_path.c.o
[ 45%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt.c.o
[ 45%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_comparable.c.o
[ 47%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_hash.c.o
[ 47%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_set.c.o
[ 47%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_map.c.o
[ 50%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_bucket.c.o
[ 50%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_trie.c.o
[ 50%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_vector.c.o
[ 52%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem.c.o
[ 52%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem_file_descriptor.c.o
[ 54%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem_directory_descriptor.c.o
[ 54%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink.c.o
[ 54%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_impl.c.o
[ 57%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_impl_unix.c.o
[ 57%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_interface.c.o
[ 59%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_symbol.c.o
[ 59%] Building C object source/metacall/CMakeFiles/metacall.dir/__/detour/source/detour.c.o
[ 59%] Building C object source/metacall/CMakeFiles/metacall.dir/__/detour/source/detour_impl.c.o
[ 61%] Building C object source/metacall/CMakeFiles/metacall.dir/__/detour/source/detour_singleton.c.o
[ 61%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect.c.o
[ 61%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_type.c.o
[ 64%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_type_id.c.o
[ 64%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_signature.c.o
[ 66%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_function.c.o
/Users/mart/metacall/core/source/reflect/source/reflect_function.c:639:39: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t'
      (aka 'unsigned long long') [-Wformat]
                printf("Allocations: %" PRIuS "\n", function_stats.allocations);
                                     ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_function.c:640:41: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t'
      (aka 'unsigned long long') [-Wformat]
                printf("Deallocations: %" PRIuS "\n", function_stats.deallocations);
                                       ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_function.c:641:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t'
      (aka 'unsigned long long') [-Wformat]
                printf("Increments: %" PRIuS "\n", function_stats.increments);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_function.c:642:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t'
      (aka 'unsigned long long') [-Wformat]
                printf("Decrements: %" PRIuS "\n", function_stats.decrements);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
[ 66%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_attribute.c.o
[ 66%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_constructor.c.o
[ 69%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_method.c.o
[ 69%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_class_visibility.c.o
[ 69%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_class.c.o
/Users/mart/metacall/core/source/reflect/source/reflect_class.c:843:39: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Allocations: %" PRIuS "\n", class_stats.allocations);
                                     ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_class.c:844:41: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Deallocations: %" PRIuS "\n", class_stats.deallocations);
                                       ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_class.c:845:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Increments: %" PRIuS "\n", class_stats.increments);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_class.c:846:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Decrements: %" PRIuS "\n", class_stats.decrements);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
[ 71%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_object.c.o
/Users/mart/metacall/core/source/reflect/source/reflect_object.c:393:39: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Allocations: %" PRIuS "\n", object_stats.allocations);
                                     ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_object.c:394:41: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Deallocations: %" PRIuS "\n", object_stats.deallocations);
                                       ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_object.c:395:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Increments: %" PRIuS "\n", object_stats.increments);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mart/metacall/core/source/reflect/source/reflect_object.c:396:38: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long')
      [-Wformat]
                printf("Decrements: %" PRIuS "\n", object_stats.decrements);
                                    ~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
[ 71%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_future.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_scope.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_context.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value.c.o
[ 76%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type.c.o
[ 76%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_id_size.c.o
[ 76%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_promotion.c.o
[ 78%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_demotion.c.o
[ 78%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_cast.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/serial/source/serial.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/serial/source/serial_impl.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/serial/source/serial_singleton.c.o
[ 83%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration.c.o
[ 83%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_singleton.c.o
[ 83%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_object.c.o
[ 85%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_impl.c.o
[ 85%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader.c.o
[ 88%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_impl.c.o
[ 88%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_env.c.o
[ 88%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_path.c.o
[ 90%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall.c.o
[ 90%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_value.c.o
[ 90%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_log.c.o
[ 92%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_allocator.c.o
[ 92%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_fork.c.o
[ 95%] Linking CXX shared library ../../libmetacall.dylib
[ 95%] Built target metacall
[ 97%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader.c.o
[ 97%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_impl.c.o
/Users/mart/metacall/core/source/loaders/py_loader/source/py_loader_impl.c:3811:6: warning: unused function 'py_loader_impl_sys_path_print' [-Wunused-function]
void py_loader_impl_sys_path_print(PyObject *sys_path_list)
     ^
1 warning generated.
[ 97%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_port.c.o
/Users/mart/metacall/core/source/loaders/py_loader/source/py_loader_port.c:595:7: warning: variable 'ret' is uninitialized when used here [-Wuninitialized]
                if (ret == NULL)
                    ^~~
/Users/mart/metacall/core/source/loaders/py_loader/source/py_loader_port.c:579:12: note: initialize the variable 'ret' to silence this warning
                void *ret;
                         ^
                          = NULL
/Users/mart/metacall/core/source/loaders/py_loader/source/py_loader_port.c:502:18: warning: unused function 'py_loader_port_await' [-Wunused-function]
static PyObject *py_loader_port_await(PyObject *self, PyObject *var_args)
                 ^
2 warnings generated.
[100%] Linking CXX shared module ../../../libpy_loader.so
[100%] Built target py_loader
```

**Comment by Prthmsh7** [comment] 2024-12-13 11:32
Hey @inimeseke,
I ran the commands twice after properly setting up the project and didn't encounter any bugs. It seems the issue is resolved now. You can go ahead and close it.
 
`
pra7hmesh@pra7hmesh-ubuntu:~/Desktop/open-source/core/build$ make py_loader
[  0%] Building C object source/metacall/CMakeFiles/metacall.dir/__/version/source/version.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/preprocessor/source/preprocessor.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment.c.o
[  2%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment_variable.c.o
[  4%] Building C object source/metacall/CMakeFiles/metacall.dir/__/environment/source/environment_variable_path.c.o
[  4%] Building C object source/metacall/CMakeFiles/metacall.dir/__/format/source/format.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/threading/source/threading.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/threading/source/threading_thread_id.c.o
[  7%] Building C object source/metacall/CMakeFiles/metacall.dir/__/threading/source/threading_mutex_pthread.c.o
[  9%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log.c.o
[  9%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_valid_size.c.o
[  9%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_map.c.o
[ 12%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_level.c.o
[ 12%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_record.c.o
[ 12%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_handle.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect.c.o
[ 14%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_impl.c.o
[ 17%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_singleton.c.o
[ 17%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format.c.o
[ 17%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_binary.c.o
[ 19%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_custom.c.o
[ 19%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_format_text.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule_async.c.o
[ 21%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_schedule_sync.c.o
[ 24%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage.c.o
[ 24%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage_batch.c.o
[ 24%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_storage_sequential.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_custom.c.o
[ 26%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_file.c.o
[ 29%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_nginx.c.o
[ 29%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_socket.c.o
[ 29%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_stdio.c.o
[ 31%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_policy_stream_syslog.c.o
[ 31%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_format.c.o
[ 31%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_schedule.c.o
[ 34%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_stream.c.o
[ 34%] Building C object source/metacall/CMakeFiles/metacall.dir/__/log/source/log_aspect_storage.c.o
[ 36%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory.c.o
[ 36%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator.c.o
[ 36%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_std.c.o
[ 39%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_std_impl.c.o
[ 39%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_nginx.c.o
[ 39%] Building C object source/metacall/CMakeFiles/metacall.dir/__/memory/source/memory_allocator_nginx_impl.c.o
[ 41%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability.c.o
[ 41%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability_path.c.o
[ 41%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability_executable_path.c.o
[ 43%] Building C object source/metacall/CMakeFiles/metacall.dir/__/portability/source/portability_library_path.c.o
[ 43%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt.c.o
[ 43%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_comparable.c.o
[ 46%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_hash.c.o
[ 46%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_set.c.o
[ 48%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_map.c.o
[ 48%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_bucket.c.o
[ 48%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_trie.c.o
[ 51%] Building C object source/metacall/CMakeFiles/metacall.dir/__/adt/source/adt_vector.c.o
[ 51%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem.c.o
[ 51%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem_file_descriptor.c.o
[ 53%] Building C object source/metacall/CMakeFiles/metacall.dir/__/filesystem/source/filesystem_directory_descriptor.c.o
[ 53%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink.c.o
[ 53%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_impl.c.o
[ 56%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_impl_unix.c.o
[ 56%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_interface.c.o
[ 56%] Building C object source/metacall/CMakeFiles/metacall.dir/__/dynlink/source/dynlink_symbol.c.o
[ 58%] Building C object source/metacall/CMakeFiles/metacall.dir/__/plugin/source/plugin.c.o
[ 58%] Building C object source/metacall/CMakeFiles/metacall.dir/__/plugin/source/plugin_descriptor.c.o
[ 58%] Building C object source/metacall/CMakeFiles/metacall.dir/__/plugin/source/plugin_impl.c.o
[ 60%] Building C object source/metacall/CMakeFiles/metacall.dir/__/plugin/source/plugin_loader.c.o
[ 60%] Building C object source/metacall/CMakeFiles/metacall.dir/__/plugin/source/plugin_manager.c.o
[ 63%] Building C object source/metacall/CMakeFiles/metacall.dir/__/detour/source/detour.c.o
[ 63%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect.c.o
[ 63%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_type.c.o
[ 65%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_type_id.c.o
[ 65%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_signature.c.o
[ 65%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_function.c.o
[ 68%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_attribute.c.o
[ 68%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_constructor.c.o
[ 68%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_memory_tracker.c.o
[ 70%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_method.c.o
[ 70%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_class_visibility.c.o
[ 70%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_class.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_object.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_future.c.o
[ 73%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_exception.c.o
[ 75%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_throwable.c.o
[ 75%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_scope.c.o
[ 78%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_context.c.o
[ 78%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value.c.o
[ 78%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_id_size.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_promotion.c.o
[ 80%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_demotion.c.o
[ 82%] Building C object source/metacall/CMakeFiles/metacall.dir/__/reflect/source/reflect_value_type_cast.c.o
[ 82%] Building C object source/metacall/CMakeFiles/metacall.dir/__/serial/source/serial.c.o
[ 82%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration.c.o
[ 85%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_singleton.c.o
[ 85%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_object.c.o
[ 85%] Building C object source/metacall/CMakeFiles/metacall.dir/__/configuration/source/configuration_impl.c.o
[ 87%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader.c.o
[ 87%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_impl.c.o
[ 87%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_host.c.o
[ 90%] Building C object source/metacall/CMakeFiles/metacall.dir/__/loader/source/loader_manager_impl.c.o
[ 90%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall.c.o
[ 92%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_value.c.o
[ 92%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_log.c.o
[ 92%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_allocator.c.o
[ 95%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_error.c.o
[ 95%] Building C object source/metacall/CMakeFiles/metacall.dir/source/metacall_fork.c.o
[ 95%] Linking CXX shared library ../../libmetacall.so
[ 95%] Built target metacall
[ 95%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader.c.o
[ 97%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_impl.c.o
[ 97%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_port.c.o
[100%] Building CXX object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_threading.cpp.o
[100%] Building C object source/loaders/py_loader/CMakeFiles/py_loader.dir/source/py_loader_dict.c.o
[100%] Linking CXX shared module ../../../libpy_loader.so
[100%] Built target py_loader
`

![issue239](https://github.com/user-attachments/assets/16bf85d2-4438-4fd3-a599-88f52744facb)

**Closed** 2024-12-13 11:48 UTC
Labels: bug
